#ifndef AX_LWIP_OPTS_H
#define AX_LWIP_OPTS_H
#define NO_SYS 1
#define SYS_LIGHTWEIGHT_PROT 0
#define MEM_ALIGNMENT 4
#define MEM_SIZE (128 * 1024)
#define PBUF_POOL_SIZE 32
#define PBUF_POOL_BUFSIZE 1600
#define LWIP_IPV4 1
#define LWIP_IPV6 0
#define LWIP_ARP 1
#define LWIP_ETHERNET 1
#define LWIP_ICMP 1
#define LWIP_RAW 1
#define LWIP_DHCP 1
#define DHCP_DOES_ARP_CHECK 1
#define LWIP_AUTOIP 0
#define LWIP_UDP 1
#define LWIP_TCP 0
#define LWIP_DNS 0
#define LWIP_NETCONN 0
#define LWIP_SOCKET 0
#define LWIP_NETIF_STATUS_CALLBACK 1
#define LWIP_NETIF_LINK_CALLBACK 1
#define LWIP_NETIF_HOSTNAME 1
#define LWIP_NETIF_TX_SINGLE_PBUF 1
#define IP_REASSEMBLY 1
#define IP_FRAG 1
#define LWIP_STATS 1
#define LWIP_NETIF_LOOPBACK 0
#endif
