#include "gx2_video.h"

#include <malloc.h>
#include <coreinit/time.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include <gx2/draw.h>
#include <gx2/enum.h>
#include <gx2/mem.h>
#include <gx2/registers.h>
#include <gx2/sampler.h>
#include <gx2/shaders.h>
#include <gx2/state.h>
#include <gx2/surface.h>
#include <gx2/texture.h>
#include <gx2/utils.h>

#include <gx2r/buffer.h>
#include <gx2r/draw.h>

#include <whb/gfx.h>
#include <whb/log.h>

/* Generated by bin2o from data/nv12.gsh. */
#include "nv12_gsh.h"

#define PLANE_BUFFERS 2
#define VERTEX_COUNT  4

typedef struct {
    float x;
    float y;
    float u;
    float v;
} VideoVertex;

typedef struct {
    int ready;
    int have_frame;

    WHBGfxShaderGroup shader;
    GX2Sampler sampler;

    GX2Texture luma_texture;
    GX2Texture chroma_texture;

    GX2RBuffer vertex_buffer;

    uint8_t *luma_buffer[PLANE_BUFFERS];
    uint8_t *chroma_buffer[PLANE_BUFFERS];

    int buffer_index;

    int width;
    int height;
    int source_stride;

    unsigned updates;
    unsigned draws;

    uint64_t copy_us_total;
    uint64_t invalidate_us_total;

    uint32_t copy_us_max;
    uint32_t invalidate_us_max;
} VideoGpu;

static VideoGpu g;

static void free_planes(void)
{
    for (int i = 0; i < PLANE_BUFFERS; ++i) {
        free(g.luma_buffer[i]);
        free(g.chroma_buffer[i]);

        g.luma_buffer[i] = NULL;
        g.chroma_buffer[i] = NULL;
    }

    memset(&g.luma_texture, 0, sizeof(g.luma_texture));
    memset(&g.chroma_texture, 0, sizeof(g.chroma_texture));

    g.width = 0;
    g.height = 0;
    g.source_stride = 0;
    g.have_frame = 0;
}

static void describe_texture(GX2Texture *texture,
                             uint32_t width,
                             uint32_t height,
                             GX2SurfaceFormat format,
                             uint32_t comp_map)
{
    memset(texture, 0, sizeof(*texture));

    texture->surface.dim = GX2_SURFACE_DIM_TEXTURE_2D;
    texture->surface.width = width;
    texture->surface.height = height;
    texture->surface.depth = 1;
    texture->surface.mipLevels = 1;
    texture->surface.format = format;
    texture->surface.aa = GX2_AA_MODE1X;
    texture->surface.use = GX2_SURFACE_USE_TEXTURE;
    texture->surface.tileMode = GX2_TILE_MODE_LINEAR_ALIGNED;
    texture->surface.swizzle = 0;

    texture->viewFirstMip = 0;
    texture->viewNumMips = 1;
    texture->viewFirstSlice = 0;
    texture->viewNumSlices = 1;
    texture->compMap = comp_map;

    GX2CalcSurfaceSizeAndAlignment(&texture->surface);
}

static int configure_planes(int width,
                            int height,
                            int source_stride)
{
    if (width == g.width &&
        height == g.height &&
        source_stride == g.source_stride) {
        return 0;
    }

    free_planes();

    describe_texture(
        &g.luma_texture,
        (uint32_t)width,
        (uint32_t)height,
        GX2_SURFACE_FORMAT_UNORM_R8,
        GX2_COMP_MAP(
            GX2_SQ_SEL_R,
            GX2_SQ_SEL_0,
            GX2_SQ_SEL_0,
            GX2_SQ_SEL_1));

    describe_texture(
        &g.chroma_texture,
        (uint32_t)(width / 2),
        (uint32_t)(height / 2),
        GX2_SURFACE_FORMAT_UNORM_R8_G8,
        GX2_COMP_MAP(
            GX2_SQ_SEL_R,
            GX2_SQ_SEL_G,
            GX2_SQ_SEL_0,
            GX2_SQ_SEL_1));

    /*
     * Zero-copy is only valid if H264DEC's stride is exactly the stride
     * GX2 expects for these linear textures.
     */
    if ((int)g.luma_texture.surface.pitch != source_stride ||
        (int)(g.chroma_texture.surface.pitch * 2u) != source_stride) {

        WHBLogPrintf(
            "gx2 video: zero-copy pitch mismatch "
            "decoder=%d y=%u uv_bytes=%u",
            source_stride,
            (unsigned)g.luma_texture.surface.pitch,
            (unsigned)(g.chroma_texture.surface.pitch * 2u));

        return -1;
    }

    GX2InitTextureRegs(
        &g.luma_texture);

    GX2InitTextureRegs(
        &g.chroma_texture);

    g.width = width;
    g.height = height;
    g.source_stride = source_stride;

    WHBLogPrintf(
        "gx2 video: ZERO-COPY %dx%d pitch=%d",
        width,
        height,
        source_stride);

    return 0;
}


int gx2_video_init(void)
{
    memset(&g, 0, sizeof(g));

    /*
     * The GSH contains exactly one vertex/pixel pair.
     */
    if (!WHBGfxLoadGFDShaderGroup(
            &g.shader,
            0,
            nv12_gsh)) {
        WHBLogPrintf(
            "gx2 video: cannot load nv12.gsh");
        return -1;
    }

    /*
     * CafeGLSL was told explicitly:
     *
     *   location 0 = position
     *   location 1 = texture coordinates
     *
     * Both live in the same interleaved vertex buffer.
     */
    g.shader.numAttributes = 2;

    GX2AttribStream *position =
        &g.shader.attributes[0];

    memset(position, 0, sizeof(*position));

    position->location = 0;
    position->buffer = 0;
    position->offset = 0;
    position->format =
        GX2_ATTRIB_FORMAT_FLOAT_32_32;
    position->type =
        GX2_ATTRIB_INDEX_PER_VERTEX;
    position->aluDivisor = 0;
    position->mask =
        GX2_SEL_MASK(
            GX2_SQ_SEL_X,
            GX2_SQ_SEL_Y,
            GX2_SQ_SEL_0,
            GX2_SQ_SEL_1);
    position->endianSwap =
        GX2_ENDIAN_SWAP_DEFAULT;

    GX2AttribStream *texcoord =
        &g.shader.attributes[1];

    *texcoord = *position;
    texcoord->location = 1;
    texcoord->offset =
        2 * sizeof(float);

    if (!WHBGfxInitFetchShader(&g.shader)) {
        WHBLogPrintf(
            "gx2 video: fetch shader init failed");

        WHBGfxFreeShaderGroup(&g.shader);
        memset(&g.shader, 0, sizeof(g.shader));
        return -1;
    }

    memset(&g.vertex_buffer,
           0,
           sizeof(g.vertex_buffer));

    g.vertex_buffer.flags =
        GX2R_RESOURCE_BIND_VERTEX_BUFFER |
        GX2R_RESOURCE_USAGE_CPU_WRITE |
        GX2R_RESOURCE_USAGE_GPU_READ;

    g.vertex_buffer.elemSize =
        sizeof(VideoVertex);

    g.vertex_buffer.elemCount =
        VERTEX_COUNT;

    if (!GX2RCreateBuffer(&g.vertex_buffer)) {
        WHBLogPrintf(
            "gx2 video: vertex buffer init failed");

        WHBGfxFreeShaderGroup(&g.shader);
        memset(&g.shader, 0, sizeof(g.shader));
        return -1;
    }

    GX2InitSampler(
        &g.sampler,
        GX2_TEX_CLAMP_MODE_CLAMP,
        GX2_TEX_XY_FILTER_MODE_LINEAR);

    g.ready = 1;

    WHBLogPrintf(
        "gx2 video: direct NV12 renderer ready, gsh=%u bytes mode=%d",
        (unsigned)nv12_gsh_size,
        (int)g.shader.vertexShader->mode);

    return 0;
}

void gx2_video_shutdown(void)
{
    free_planes();

    if (g.vertex_buffer.buffer) {
        GX2RDestroyBufferEx(
            &g.vertex_buffer,
            0);

        memset(&g.vertex_buffer,
               0,
               sizeof(g.vertex_buffer));
    }

    if (g.shader.vertexShader ||
        g.shader.pixelShader ||
        g.shader.fetchShaderProgram) {
        WHBGfxFreeShaderGroup(&g.shader);
    }

    memset(&g, 0, sizeof(g));
}

int gx2_video_update(const uint8_t *luma,
                     const uint8_t *chroma,
                     int stride,
                     int width,
                     int height)
{
    if (!g.ready ||
        !luma ||
        !chroma ||
        width <= 0 ||
        height <= 0 ||
        stride < width ||
        (width & 1) ||
        (height & 1)) {
        return -1;
    }

    if (configure_planes(
            width,
            height,
            stride) != 0) {
        return -1;
    }

    /*
     * H264DEC already wrote the NV12 pixels here.
     *
     * Just point GX2 at them.
     */
    const OSTime bind_start =
        OSGetSystemTime();

    g.luma_texture.surface.image =
        (void *)luma;

    g.chroma_texture.surface.image =
        (void *)chroma;

    const uint32_t bind_us =
        (uint32_t)OSTicksToMicroseconds(
            OSGetSystemTime() - bind_start);

    /*
     * Keep the old "copy" metric field for compatibility with the
     * diagnostics struct, but it now measures the zero-copy bind.
     */
    g.copy_us_total += bind_us;

    if (bind_us > g.copy_us_max) {
        g.copy_us_max = bind_us;
    }

    /*
     * Make sure GX2 sees the decoder-produced picture.
     * This is tiny compared with the old ~1.35 MiB memcpy.
     */
    const OSTime invalidate_start =
        OSGetSystemTime();

    GX2Invalidate(
        GX2_INVALIDATE_MODE_CPU_TEXTURE,
        (void *)luma,
        (uint32_t)(
            (size_t)stride *
            (size_t)height *
            3u / 2u));

    const uint32_t invalidate_us =
        (uint32_t)OSTicksToMicroseconds(
            OSGetSystemTime() -
            invalidate_start);

    g.invalidate_us_total += invalidate_us;

    if (invalidate_us > g.invalidate_us_max) {
        g.invalidate_us_max =
            invalidate_us;
    }

    g.have_frame = 1;
    g.updates++;

    return 0;
}


static int update_vertices(int target_width,
                           int target_height)
{
    if (!g.have_frame ||
        target_width <= 0 ||
        target_height <= 0) {
        return -1;
    }

    int x = 0;
    int y = 0;
    int w = target_width;
    int h = target_height;

    /*
     * Same FIT behaviour as the old SDL renderer.
     */
    if ((long long)g.width *
            target_height >
        (long long)g.height *
            target_width) {

        h = (int)(
            (long long)target_width *
            g.height /
            g.width);

        y = (target_height - h) / 2;

    } else {
        w = (int)(
            (long long)target_height *
            g.width /
            g.height);

        x = (target_width - w) / 2;
    }

    const float left =
        ((float)x /
         (float)target_width) *
            2.0f - 1.0f;

    const float right =
        ((float)(x + w) /
         (float)target_width) *
            2.0f - 1.0f;

    const float top =
        1.0f -
        ((float)y /
         (float)target_height) *
            2.0f;

    const float bottom =
        1.0f -
        ((float)(y + h) /
         (float)target_height) *
            2.0f;

    VideoVertex *v =
        (VideoVertex *)
        GX2RLockBufferEx(
            &g.vertex_buffer,
            0);

    if (!v) {
        return -1;
    }

    /*
     * Triangle strip:
     *
     * bottom-left, bottom-right,
     * top-left,    top-right
     */
    v[0] = (VideoVertex){
        left, bottom, 0.0f, 1.0f
    };

    v[1] = (VideoVertex){
        right, bottom, 1.0f, 1.0f
    };

    v[2] = (VideoVertex){
        left, top, 0.0f, 0.0f
    };

    v[3] = (VideoVertex){
        right, top, 1.0f, 0.0f
    };

    GX2RUnlockBufferEx(
        &g.vertex_buffer,
        0);

    return 0;
}

int gx2_video_draw(int target_width,
                   int target_height)
{
    if (!g.ready ||
        !g.have_frame) {
        return -1;
    }

    if (update_vertices(
            target_width,
            target_height) != 0) {
        return -1;
    }

    /*
     * SDL draws the menu before/after this raw GX2 pass and may leave
     * viewport/scissor state behind.
     *
     * Unlike shaders/blend/depth, these were not restored previously.
     * That can leave parts of a previous menu frame untouched by the
     * following video frame ("ghost" rectangles).
     */
    GX2SetViewport(
        0.0f,
        0.0f,
        (float)target_width,
        (float)target_height,
        0.0f,
        1.0f);

    GX2SetScissor(
        0,
        0,
        target_width,
        target_height);

    /*
     * The video is opaque.
     *
     * Don't inherit SDL's current blend/depth/cull state because it can
     * vary depending on what the UI drew immediately before us.
     */
    GX2SetDepthOnlyControl(
        FALSE,
        FALSE,
        GX2_COMPARE_FUNC_ALWAYS);

    GX2SetColorControl(
        GX2_LOGIC_OP_COPY,
        0xFF,
        FALSE,
        TRUE);

    GX2SetBlendControl(
        GX2_RENDER_TARGET_0,
        GX2_BLEND_MODE_ONE,
        GX2_BLEND_MODE_ZERO,
        GX2_BLEND_COMBINE_MODE_ADD,
        FALSE,
        GX2_BLEND_MODE_ONE,
        GX2_BLEND_MODE_ZERO,
        GX2_BLEND_COMBINE_MODE_ADD);

    GX2SetCullOnlyControl(
        GX2_FRONT_FACE_CCW,
        FALSE,
        FALSE);

    /*
     * Use exactly the mode encoded by the compiler.
     */
    GX2SetShaderMode(
        g.shader.vertexShader->mode);

    GX2SetFetchShader(
        &g.shader.fetchShader);

    GX2SetVertexShader(
        g.shader.vertexShader);

    GX2SetPixelShader(
        g.shader.pixelShader);

    GX2SetPixelTexture(
        &g.luma_texture,
        0);

    GX2SetPixelSampler(
        &g.sampler,
        0);

    GX2SetPixelTexture(
        &g.chroma_texture,
        1);

    GX2SetPixelSampler(
        &g.sampler,
        1);

    GX2RSetAttributeBuffer(
        &g.vertex_buffer,
        0,
        sizeof(VideoVertex),
        0);

    GX2DrawEx(
        GX2_PRIMITIVE_MODE_TRIANGLE_STRIP,
        VERTEX_COUNT,
        0,
        1);

    g.draws++;

    return 0;
}

void gx2_video_stats(Gx2VideoStats *out)
{
    if (!out) {
        return;
    }

    memset(out, 0, sizeof(*out));

    out->updates = g.updates;
    out->draws = g.draws;

    if (g.updates) {
        out->copy_avg_us =
            (uint32_t)(g.copy_us_total /
                       g.updates);

        out->invalidate_avg_us =
            (uint32_t)(g.invalidate_us_total /
                       g.updates);
    }

    out->copy_max_us = g.copy_us_max;
    out->invalidate_max_us =
        g.invalidate_us_max;
}
